@startuml to_be
!theme materia
skinparam actorStyle awesome
skinparam packageStyle rectangle

title Автоматическая рассылка

[Генератор] -> [API] : Еженедельная\nрассылка.
[API] -> [Отправщик\n(воркер)] : Информация \nо событии.
[Отправщик\n(воркер)] -> [Пользователь] : Уведомление.

@enduml
