@startuml to_be
!theme materia
skinparam actorStyle awesome
skinparam packageStyle rectangle

title Рассылка о UGC

[UGC Система] -> [API] : Запрос \nпро новый \nлайк.
[API] -> [Отправщик\n(воркер)] : Информация \nо событии.
[Отправщик\n(воркер)] -> [Пользователь] : Уведомление.

@enduml
