# Generated by Django 4.0.4 on 2022-08-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_admin', '0004_filmwork_persons_alter_personfilmwork_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElasticWatcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watcher', models.CharField(max_length=32, unique=True)),
                ('modified_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'content"."elastic_watcher',
            },
        ),
    ]
