# Generated by Django 4.0.4 on 2022-08-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_admin', '0005_elasticwatcher'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElasticState',
            fields=[
                ('namestamp', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'content"."elastic_state',
            },
        ),
        migrations.DeleteModel(
            name='ElasticWatcher',
        ),
    ]
