"""auth_event

Revision ID: fe8a05a32372
Revises: ac8e4e98a1b7
Create Date: 2023-02-17 03:40:23.561191

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fe8a05a32372'
down_revision = 'ac8e4e98a1b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_confirmation', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_confirmation')
    # ### end Alembic commands ###
