"""email_confirm

Revision ID: 95cef2d8b5b5
Revises: ac8e4e98a1b7
Create Date: 2023-02-20 22:22:55.623793

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '95cef2d8b5b5'
down_revision = 'ac8e4e98a1b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_confirmation', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('confirmation_code', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_unique_constraint('users_confirmation_code_key', 'users', ['confirmation_code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmation_code')
    op.drop_column('users', 'email_confirmation')

    # ### end Alembic commands ###
